### ISSUE TITLE
Support `wasm32-wasip2` on the stable channel

### ISSUE THREAD

**Issue by brooksmtownsend** [wacker-dev/waki#25]
Hey! 👋🏻 

First of all, I'm hugely inspired by how simple this crate makes wasi:http in Rust. It looks really nice, and your implementations feel nice and idiomatic. I was going to do something similar to this for https://wasmcloud.com/, but it looks like you've already done a lot of what I was hoping for 😄

Since this crate depends on `url`, I'm pretty familiar with one of the small hiccups that affected `wasm32-wasip2` on the nightly toolchain https://github.com/servo/rust-url/pull/960. I just filed an upstream PR to fix this for the stable toolchain as well https://github.com/servo/rust-url/pull/983, but I want to be sensitive to how prevalent the `url` crate is and that this target just landed in Rust 1.82.0. I would love to use this library, selfishly for https://crates.io/crates/wasmcloud-component. To be clear, we're using the wasmcloud-component essentially as a stopgap for things that don't exist in [the wasi crate](https://crates.io/crates/wasi) and its wrappers are all wasi-p2 compatible.

Anyways, do you have any thoughts on ways we can support this crate for `wasm32-wasip2` on the stable channel in the meantime?

**Comment by brooksmtownsend** [comment]
I suppose another possible rabbit hole here is that the request code looks similarly structured to reqwest https://github.com/seanmonstar/reqwest/issues/2294, what do you think about collaborating there to add support to that library, or are you more interested in having a wasi-first library here

**Comment by iawia002** [comment]
Hi @brooksmtownsend, thanks for your interest in this project, I do want to have a wasi-first library here.

Actually, I have already been working on fixing this issue. Since the release of Rust 1.82, I have noticed the problem, and I have also seen your patch in the rust-url crate. I am planning to stop relying on the `url` crate. A new version will be released in the next few days.

**Comment by iawia002** [comment]
I have released [v0.4.0](https://docs.rs/waki/0.4.0/waki/), please give it a try.

**Comment by brooksmtownsend** [comment]
Amazing! I'll give it a shot today. Great Monday present @iawia002
