### ISSUE TITLE
Buffer too large for blocking-write-and-flush (expected at most 4096)

### ISSUE THREAD

**Issue by seungjin** [wacker-dev/waki#32]
Having `Buffer too large for blocking-write-and-flush (expected at most 4096)` error due to `a write of up to 4096 bytes, and then flush the stream.`
https://docs.rs/wasi/latest/wasi/io/streams/struct.OutputStream.html#method.blocking_write_and_flush

**Comment by iawia002** [comment]
Fixed in [v0.4.1](https://github.com/wacker-dev/waki/releases/tag/v0.4.1), please give it a try.

**Comment by seungjin** [comment]
> Fixed in [v0.4.1](https://github.com/wacker-dev/waki/releases/tag/v0.4.1), please give it a try.

Not response but request(outgoing_handler). Using the most recent one with git path but request side is getting buffer too large error.

**Comment by iawia002** [comment]
Oh sorry, I misunderstood, I will fix it tomorrow.

**Comment by seungjin** [comment]
> Oh sorry, I misunderstood, I will fix it tomorrow.


This did not work though.
It was fine with 4096 byte but once it goes over 4096bytes, OutgoingBody::finish did not work.

https://github.com/seungjin/waki/blob/4dddb0ba6ba6e10b14ecdbe1940c75a5dfb5d171/waki/src/request.rs#L260

**Comment by iawia002** [comment]
I have released [v0.5.0](https://github.com/wacker-dev/waki/releases/tag/v0.5.0), please give it a try.
